server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: "change-me-super-long-secret-string-for-hs256-demo-only-please"
    issuer: "secure-api-audit"
    ttlMinutes: 120

logging:
  level:
    root: INFO
